/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/492dabaf-1e36-4ede-97a2-885fce8ef031 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float current;
  float volt;
  int cost;
  int unit;
  bool due;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}

/*
  Since V is READ_WRITE variable, onVChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onVChange()  {
  // Add your code here to act upon V change
}

/*
  Since I is READ_WRITE variable, onIChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onIChange()  {
  // Add your code here to act upon I change
}

/*
  Since A is READ_WRITE variable, onAChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onAChange()  {
  // Add your code here to act upon A change
}

/*
  Since Unit is READ_WRITE variable, onUnitChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onUnitChange()  {
  // Add your code here to act upon Unit change
}

/*
  Since Volt is READ_WRITE variable, onVoltChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onVoltChange()  {
  // Add your code here to act upon Volt change
}

/*
  Since Cost is READ_WRITE variable, onCostChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCostChange()  {
  // Add your code here to act upon Cost change
}

/*
  Since Current is READ_WRITE variable, onCurrentChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCurrentChange()  {
  // Add your code here to act upon Current change
}

/*
  Since Due is READ_WRITE variable, onDueChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onDueChange()  {
  // Add your code here to act upon Due change
}
