//email r.varadhan07@gmail.com
//Your username is smartenergy321_123
//Projectiot@2025

// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

#include <EEPROM.h>
#include "EmonLib.h"

#include<LiquidCrystal.h>

int u, c;
int Vrms1=230;
LiquidCrystal lcd(22, 21, 19, 18, 5, 4);


// Create an instance of the EnergyMonitor library
EnergyMonitor emon;
float kWh = 0;
unsigned long lastmillis = millis();

// Voltage and current sensor calibration factors
#define vCalibration 103.43  // Adjust based on ZMPT101B calibration
#define currCalibration 2.50  // Adjust based on ACS712 30A calibration




const char DEVICE_LOGIN_NAME[]  = "dc0a9c3d-c8c2-48f2-a32c-73e262a0ec5d";
const char SSID[]               = "projectiot";    // Network SSID (name)
const char PASS[]               = "123456789";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "T2HJ4qw9#rDIR#jRN0A@BiH9M";    // Secret device password

void onCurrentChange();
void onVoltChange();
void onCostChange();
void onUnitChange();
void onDueChange();

float current;
float volt;
int cost;
int unit;
bool due;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(current, READWRITE, ON_CHANGE, onCurrentChange);
  ArduinoCloud.addProperty(volt, READWRITE, ON_CHANGE, onVoltChange);
  ArduinoCloud.addProperty(cost, READWRITE, ON_CHANGE, onCostChange);
  ArduinoCloud.addProperty(unit, READWRITE, ON_CHANGE, onUnitChange);
  ArduinoCloud.addProperty(due, READWRITE, ON_CHANGE, onDueChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);


void myTimerEvent() {
  // Calculate voltage and current
  emon.calcVI(20, 2000); // Calculate Vrms and Irms

  float Vrms = emon.Vrms; // Vrms is calculated by EmonLib
  float Irms = emon.Irms; // Irms is calculated by EmonLib
  current=Irms;
  volt=Vrms;
  // Print values to Serial Monitor
  Serial.print('V');
  Serial.print("Vrms: ");
  Serial.print(Vrms1);
//Serial.print(" V\t");

  Serial.print('I');
  Serial.print("Irms: ");
  Serial.print(Irms, 4);
  Serial.print(" A\t");


  // Store values in EEPROM
  EEPROM.put(0, Vrms);
  EEPROM.put(4, Irms);

  lcd.setCursor(0, 0);
  lcd.print("V:230");
 // lcd.print(, 2);
  //lcd.print("V");
  lcd.setCursor(8, 0);
  lcd.print("I:");
  lcd.print(Irms, 4);
  lcd.print("A");

  lastmillis = millis();
}

void setup() {
  Serial.begin(9600);  // Initialize serial communication
  lcd.begin(16, 2);
  initProperties();
  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  // Initialize EmonLib with correct pins and calibration
  emon.voltage(35, vCalibration, 1.7);  // ZMPT101B voltage input pin, calibration factor
  emon.current(34, currCalibration);     // ACS712 current input pin, calibration factor

  pinMode(33, INPUT);
  pinMode(14, OUTPUT);
  pinMode(12, OUTPUT);
  pinMode(15, OUTPUT);
  // Initial LCD display
  lcd.setCursor(0, 0);
  lcd.print("  Smart Energy  ");
  lcd.setCursor(0, 1);
  lcd.print("  Meter via IOT ");
  delay(3000);
  lcd.clear();

}

void loop() {
  ArduinoCloud.update();
  myTimerEvent();
  int s = analogRead(33);
  int a = s / 4;
  Serial.println(a);
  Serial.print("UNIT; ");
  Serial.print(u);
  Serial.print(", COST; ");
  Serial.println(c);
  cost=c;
  unit=u;



  if (a >= 0 && a < 100)
  {
    Serial.println('a');
    lcd.setCursor(0, 1);
    lcd.print("U:0  ");
    lcd.setCursor(6, 1);
    lcd.print("      ");
    u = 0;
    c = 0;
    digitalWrite(15, LOW);
    due=true;
    lcd.setCursor(13, 1);
    lcd.print("ND");

  }
  else if (a > 100 && a < 200)
  {
    Serial.println('a');
    lcd.setCursor(0, 1);
    lcd.print("U:100");
    lcd.setCursor(6, 1);
    lcd.print("Rs:120");
    u = 100;
    c = 120;
    digitalWrite(15, LOW);
    due=true;
    lcd.setCursor(13, 1);
    lcd.print("ND");

  }
  else if (a > 200 && a < 300)
  {
    Serial.println('a');
    lcd.setCursor(0, 1);
    lcd.print("U:110");
    lcd.setCursor(6, 1);
    lcd.print("Rs:220");
    u = 110;
    c = 220;
    digitalWrite(27, LOW);
    due=true;
    lcd.setCursor(13, 1);
    lcd.print("ND");

  }
  else if (a > 300 && a < 400)
  {
    Serial.println('a');
    lcd.setCursor(0, 1);
    lcd.print("U:120");
    lcd.setCursor(6, 1);
    lcd.print("Rs:240");
    u = 120;
    c = 240;
    digitalWrite(27, LOW);
    due=true;
    lcd.setCursor(13, 1);
    lcd.print("ND");

  }
  else if (a > 400 && a < 500)
  {
    Serial.println('a');
    lcd.setCursor(0, 1);
    lcd.print("U:130");
    lcd.setCursor(6, 1);
    lcd.print("Rs:260");
    u = 130;
    c = 260;
    digitalWrite(27, LOW);
    due=true;
    lcd.setCursor(13, 1);
    lcd.print("ND");

  }
  else if (a > 500 && a < 600)
  {
    Serial.println('a');
    lcd.setCursor(0, 1);
    lcd.print("U:140");
    lcd.setCursor(6, 1);
    lcd.print("Rs:280");
    u = 140;
    c = 280;
    digitalWrite(27, LOW);
    due=true;
    lcd.setCursor(13, 1);
    lcd.print("ND");
  }
  else if (a > 600 && a < 700)
  {
    Serial.println('a');
    lcd.setCursor(0, 1);
    lcd.print("U:150");
    lcd.setCursor(6, 1);
    lcd.print("Rs:300");
    u = 150;
    c = 300;
    digitalWrite(27, LOW);
    due=true;
    lcd.setCursor(13, 1);
    lcd.print("ND");

  }
  else if (a > 700 && a < 800)
  {
    Serial.println('a');
    lcd.setCursor(0, 1);
    lcd.print("U:160");
    lcd.setCursor(6, 1);
    lcd.print("Rs:320");
    u = 160;
    c = 320;
    digitalWrite(27, LOW);
    due=true;
    lcd.setCursor(13, 1);
    lcd.print("ND");

  }
  else if (a > 800 && a < 900)
  {
    Serial.println('a');
    lcd.setCursor(0, 1);
    lcd.print("U:170");
    lcd.setCursor(6, 1);
    lcd.print("Rs:340");
    u = 170;
    c = 340;
    digitalWrite(27, LOW);
    due=true;
        lcd.setCursor(13, 1);
    lcd.print("ND");
  }
  else if (a > 900)
  {
    Serial.println('A');
    lcd.setCursor(0, 1);
    lcd.print("U:180");
    lcd.setCursor(6, 1);
    lcd.print("Rs:360");
    u = 180;
    c = 360;
    delay(3000);
    lcd.setCursor(13, 1);
    lcd.print("OD");
    digitalWrite(15, HIGH);
    due=false;
  }
  delay(500);
}




void onUnitChange()  {}
void onVoltChange()  {}
void onCostChange()  {}
void onCurrentChange()  {}
void onDueChange()  {}