// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "dc0a9c3d-c8c2-48f2-a32c-73e262a0ec5d";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onCurrentChange();
void onVoltChange();
void onCostChange();
void onUnitChange();
void onDueChange();

float current;
float volt;
int cost;
int unit;
bool due;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(current, READWRITE, ON_CHANGE, onCurrentChange);
  ArduinoCloud.addProperty(volt, READWRITE, ON_CHANGE, onVoltChange);
  ArduinoCloud.addProperty(cost, READWRITE, ON_CHANGE, onCostChange);
  ArduinoCloud.addProperty(unit, READWRITE, ON_CHANGE, onUnitChange);
  ArduinoCloud.addProperty(due, READWRITE, ON_CHANGE, onDueChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);